### ISSUE TITLE
Modify HTML title in blog posts

### ISSUE THREAD

**Issue by Marc-RF** [villoro/villoro.com#74]
It could be nice to add the title of the blog post in the HTML head title.

In the current situation it is not possible to differentiate pages when opening multiple tabs, as they all have "Villoro" in the title.

**Comment by villoro** [comment]
Solved in the [PR 75](https://github.com/villoro/villoro.com/pull/75).

It will go live in the next release (0-5 days).

Sorry for playing with the assignment, I got confused with another page.
